# Generated by Django 3.1.1 on 2022-10-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0017_substancepropertydatapoint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubstanceaddlog',
            name='failed_data_entry',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubstanceaddlog',
            name='succeed_data_entry',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubstanceaddlog',
            name='total_data_in_file',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubstanceaddlog',
            name='object_type',
            field=models.CharField(choices=[('uses_and_application', 'Uses And Application'), ('product', 'Product')], default='uses_and_application', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubstanceaddlog',
            name='process_type',
            field=models.CharField(choices=[('substance_add', 'Substance Add'), ('product_related_substances_add', 'Product Related Substances Add')], default='substance_add', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubstanceaddlog',
            name='status',
            field=models.CharField(choices=[('in_queue', 'In Queue'), ('success', 'Success'), ('in_progress', 'In Progress'), ('fail', 'Fail')], default='in_queue', max_length=20),
        ),
    ]
